name: Publish image to Dockerhub

on:
  release:
    types: [published]

jobs:
  build:
    env:
      IMAGE_NAME: bahetiamit/yq
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release tag      
        uses: oprypin/find-latest-tag@v1
        with:
          repository: bahetiamit/yq  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
        id: yq  
        
      - name: Clone source code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.yq.outputs.tag }}
      
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: index.docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1.5.0
        with:
          buildx-version: v0.4.1
      
      - name: Build and push image
        run: |
          IMAGE_VERSION="$(git describe --tags --abbrev=0)"
          SHORT_SHA1=$(git rev-parse --short HEAD)
          PLATFORMS="linux/amd64,linux/ppc64le,linux/s390x"
          echo "Building and pushing version ${IMAGE_VERSION} of image ${IMAGE_NAME}"
          docker buildx build --platform "${PLATFORMS}" -t "${IMAGE_NAME}:${IMAGE_VERSION}-${SHORT_SHA1}" \
            --push .
    
